remote_theme: zendesk/jekyll-theme-zendesk-garden@main
title: Roadbike-Game Docs
description: Documents
auto_page_title: false
sidebar:
    - top
    - label: デザイン
      children:
          - design-client
          - design-config
          - design-data
          - design-execute-command
          - design-connection
          - design-commands
          - design-events
    - label: クライアント
      children:
          - client-sensor
          - label: Sensors
            children:
                - client-sensor-pedalpower
                - label: Minecraft
                  children:
                      - client-sensor-minecraft-seed
          - label: Commanders
            children:
                - client-commander
          - label: Executors
            children:
                - client-executor
                - label: Minecraft
                  children:
                      - client-executor-minecraft-seed
          - label: Displays
            children:
                - client-display