remote_theme: zendesk/jekyll-theme-zendesk-garden@main
title: Roadbike-Game Docs
description: Documents
auto_page_title: false
sidebar:
    - top
    - label: デザイン
      children:
          - design-client
          - design-config
          - design-connection
          - design-commands
          - design-events
    - label: クライアント
      children:
          - label: Sensor
            children:
                - client-sensor
                - client-sensor-pedalpower
                - label: Minecraft
                  children:
                      - client-sensor-minecraft-seed
          - label: Controller
            children:
                - client-controller
          - label: Emulator
            children:
                - client-emulator
                - label: Minecraft
                  children:
                      - client-emulator-minecraft-seed
          - label: Display
            children:
                - client-display
